version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 5
    groups:
      django:
        patterns:
          - "django*"
      dev-tooling:
        patterns:
          - "pytest*"
          - "ruff"
          - "tox"
          - "build"
          - "twine"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 3
