"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'test-only-not-secret'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cotton',
    'django_cotton_gallery',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # Gallery's own context processor — exposes
                # `cotton_gallery.{extra_css,extra_js,dependencies}` so the
                # hero badges and asset injection blocks render. Without
                # this, the gallery loads but its hero shows only the
                # hardcoded "Django Cotton" badge.
                'django_cotton_gallery.context_processors.gallery_assets',
            ],
            'loaders': [
                (
                    'django.template.loaders.cached.Loader',
                    [
                        'django_cotton.cotton_loader.Loader',
                        'django.template.loaders.filesystem.Loader',
                        'django.template.loaders.app_directories.Loader',
                    ],
                ),
            ],
            'builtins': ['django_cotton.templatetags.cotton'],
        },
    },
]

COTTON_SNAKE_CASED_NAMES = False  # this demo's choice — kebab-case filenames map 1:1 to tags. Both styles work.

# Inject Tailwind, HTMX, Alpine into the gallery preview surface so the demo
# components above render with their actual styling.
DJANGO_COTTON_GALLERY_EXTRA_CSS = []
DJANGO_COTTON_GALLERY_EXTRA_JS = [
    "https://cdn.tailwindcss.com",
    "https://unpkg.com/htmx.org@1.9.10",
    "https://unpkg.com/alpinejs@3.13.10/dist/cdn.min.js",
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        # BASE_DIR is src/demo/; keep the dev sqlite file at the repo root by choice.
        'NAME': BASE_DIR.parent.parent / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en'

LANGUAGES = [
    ('eu', 'Euskara'),
    ('es', 'Español'),
    ('en', 'English'),
    ('fr', 'Français'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# ── django-cotton-gallery ────────────────────────────────────────────────
# Opt in to scanning the project's templates so the Insights dashboard can
# compute zombies / most-referenced and the detail page can list which
# consumer templates use each component. Read-only, dev-only — only the
# template paths surface in the gallery UI, never their contents.
DJANGO_COTTON_GALLERY_SCAN_EXTERNAL_USERS = True
